# Generated by Django 2.2.6 on 2021-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210716_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
